import type { Metadata, Viewport } from "next";
import { Inter, Archivo, IBM_Plex_Mono } from "next/font/google";
import { site } from "@/lib/site";
import { TermsGate } from "@/components/TermsGate";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans", display: "swap" });
const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  weight: ["500", "600", "700", "800", "900"],
  display: "swap",
});
const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-plex-mono",
  weight: ["400", "500"],
  display: "swap",
});

const TITLE = `${site.name} — Invisible AI Copilot for Meetings & Interviews`;

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: TITLE,
    template: `%s · ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  manifest: "/manifest.webmanifest",
  referrer: "origin-when-cross-origin",
  formatDetection: { email: false, telephone: false, address: false },
  keywords: [
    "Trapotato",
    "invisible AI assistant",
    "AI interview assistant",
    "AI meeting copilot",
    "interview copilot",
    "stealth AI assistant",
    "undetectable interview AI",
    "real-time AI answers",
    "live meeting transcription",
    "coding interview helper",
    "screen-share invisible overlay",
    "bring your own AI keys",
    "Cluely alternative",
  ],
  authors: [{ name: site.name, url: site.url }],
  creator: site.name,
  publisher: site.name,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: site.url,
    siteName: site.name,
    title: TITLE,
    description: site.description,
    // og:image (and twitter:image) are generated by app/opengraph-image.tsx and
    // applied to every route automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} — Invisible AI Copilot`,
    description: site.description,
  },
  appleWebApp: { capable: true, title: site.name, statusBarStyle: "black-translucent" },
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/logo.png",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "technology",
};

export const viewport: Viewport = {
  themeColor: "#0B0C0F",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${archivo.variable} ${plexMono.variable}`}>
      <body>
        {children}
        <TermsGate />
      </body>
    </html>
  );
}
